# Generated by Django 4.2.23 on 2025-07-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0002_remove_personalinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
