# Generated by Django 4.2.23 on 2025-07-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0003_alter_adminuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
            ],
        ),
    ]
