# Generated by Django 4.2.23 on 2025-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counseling_app', '0004_alter_adminuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('counselor', 'Counselor'), ('registrar', 'Registrar'), ('super_admin', 'Super Admin')], default='counselor', max_length=20),
        ),
    ]
